<?php

return [
    // Prodotti per Trattoria delle Eccellenze di Eugenio

    [
        'restaurant_id' => '1',
        'name' => 'Pasta alla Carbonara',
        'description' => 'La classica pasta italiana con uova, pancetta, formaggio e pepe nero.',
        'price' => 12.99,
        'img' => 'carbonara.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Pizza Margherita',
        'description' => 'La tradizionale pizza napoletana con pomodoro, mozzarella e basilico.',
        'price' => 9.99,
        'img' => 'margherita.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Tiramisù',
        'description' => 'Il classico dolce italiano fatto con savoiardi, caffè, mascarpone e cacao.',
        'price' => 6.99,
        'img' => 'tiramisu.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Risotto ai Funghi Porcini',
        'description' => 'Risotto cremoso con funghi porcini freschi e prelibato parmigiano.',
        'price' => 15.99,
        'img' => 'risotto.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Bruschetta al Pomodoro',
        'description' => 'Pane tostato con pomodoro fresco, aglio, basilico e olio extravergine di oliva.',
        'price' => 7.99,
        'img' => 'bruschetta.jpg',
        'visible' => true,
    ],
    // Prodotti per Marco's Mamma Mia Trattoria
    [
        'restaurant_id' => '2',
        'name' => 'Bistecca alla Fiorentina',
        'description' => 'La celebre bistecca toscana, cucinata alla griglia e servita al sangue.',
        'price' => 29.99,
        'img' => 'bistecca.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Pappa al Pomodoro',
        'description' => 'Zuppa toscana a base di pane raffermo, pomodoro, aglio e basilico.',
        'price' => 8.99,
        'img' => 'pappa.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Ribollita',
        'description' => 'Zuppa toscana riscaldata con pane raffermo, verdure e fagioli.',
        'price' => 10.99,
        'img' => 'ribollita.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Crostini Toscani',
        'description' => 'Pane toscano abbrustolito con fegatini di pollo e salvia.',
        'price' => 6.99,
        'img' => 'crostini.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Cantucci con Vin Santo',
        'description' => 'Biscotti toscani croccanti serviti con il tradizionale vino dolce Vin Santo.',
        'price' => 5.99,
        'img' => 'cantucci.jpg',
        'visible' => true,
    ],

    //Raoul
    [
        'restaurant_id' => '3',
        'name' => 'Sashimi Misto',
        'description' => 'Assortimento di pesce crudo fresco, tagliato a fette sottili e servito con salsa di soia e wasabi.',
        'price' => 18.99,
        'img' => 'sashimi.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Tempura Mista',
        'description' => 'Assortimento di verdure e frutti di mare fritti in pastella leggera e croccante.',
        'price' => 14.99,
        'img' => 'tempura.jpg',
        'visible' => false,
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Nigiri Sushi',
        'description' => 'Risotto di sushi con fettine di pesce crudo sopra, preparato con cura da esperti chef giapponesi.',
        'price' => 22.99,
        'img' => 'nigiri.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Uramaki California',
        'description' => 'Rotolo di sushi con avocado, granchio, cetriolo e maionese, avvolto in alga nori e riso.',
        'price' => 16.99,
        'img' => 'uramaki.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Ramen al Tonkotsu',
        'description' => 'Zuppa di noodle giapponese con brodo di maiale, pancetta, uovo sodo e cipollotti.',
        'price' => 20.99,
        'img' => 'ramen.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Tortellini in Brodo',
        'description' => 'Pasta fresca ripiena di carne, servita in un brodo caldo e profumato.',
        'price' => 13.99,
        'img' => 'tortellini.jpg',
        'visible' => false,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Tagliatelle al Ragu',
        'description' => 'Tagliatelle fatte in casa con un ricco sugo di carne cotto lentamente.',
        'price' => 15.99,
        'img' => 'tagliatelle.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Parmigiana di Melanzane',
        'description' => 'Strati di melanzane fritte, pomodoro, mozzarella e parmigiano gratinato al forno.',
        'price' => 11.99,
        'img' => 'parmigiana.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Cotoletta alla Bolognese',
        'description' => 'Cotoletta di maiale impanata e fritta, servita con contorno di patatine fritte.',
        'price' => 17.99,
        'img' => 'cotoletta.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Panna Cotta',
        'description' => 'Dolce cremoso al gusto di vaniglia, servito con salsa al cioccolato e frutti di bosco.',
        'price' => 7.99,
        'img' => 'pannacotta.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '5',
        'name' => 'Risotto ai Frutti di Mare',
        'description' => 'Risotto cremoso con una varietà di frutti di mare freschi e prezzemolo.',
        'price' => 19.99,
        'img' => 'risotto_mare.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '5',
        'name' => 'Cotoletta alla Milanese',
        'description' => 'Cotoletta di vitello impanata e fritta, servita con fette di limone e insalata mista.',
        'price' => 18.99,
        'img' => 'cotoletta_milano.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '5',
        'name' => 'Minestrone alla Milanese',
        'description' => 'Zuppa milanese riscaldante con una varietà di verdure fresche e pasta piccola.',
        'price' => 10.99,
        'img' => 'minestrone_milano.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '5',
        'name' => 'Polenta con Funghi Porcini',
        'description' => 'Polenta calda e cremosa servita con un saporito ragù di funghi porcini.',
        'price' => 16.99,
        'img' => 'polenta_funghi.jpg',
        'visible' => true,
    ],
    [
        'restaurant_id' => '5',
        'name' => 'Tiramisù',
        'description' => 'Il classico dolce italiano fatto con savoiardi, caffè, mascarpone e cacao.',
        'price' => 6.99,
        'img' => 'tiramisu_giorgio.jpg',
        'visible' => true,
    ],
];
