<?php
return

    [
        // Ristorante 1
        [
            'restaurant_id' => '1',
            'name' => 'Pasta alla Carbonara',
            'description' => 'La classica pasta italiana con uova, pancetta, formaggio e pepe nero.',
            'price' => 12.99,
            'img' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/11/ricetta-spaghetti-carbonara/_jcr_content/header-par/image_single.img.jpg/1617198167116.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza con pomodoro, mozzarella di bufala, basilico fresco e olio d\'oliva.',
            'price' => 9.99,
            'img' => 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'visible' => true,
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Tiramisù',
            'description' => 'Dolce italiano composto da savoiardi inzuppati nel caffè, crema di mascarpone e cacao amaro.',
            'price' => 6.99,
            'img' => 'https://images.unsplash.com/photo-1631206753348-db44968fd440?q=80&w=1325&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'visible' => true,
        ],

        // Ristorante 2
        [
            'restaurant_id' => '2',
            'name' => 'Bistecca alla Fiorentina',
            'description' => 'Fiorentina di manzo grigliata, servita al sangue e condita con sale grosso e olio d\'oliva.',
            'price' => 25.99,
            'img' => 'https://images.unsplash.com/photo-1683315445782-48b2459c234d?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'visible' => true,
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Ribollita',
            'description' => 'Zuppa toscana a base di pane raffermo, verdure miste, fagioli e cavolo nero.',
            'price' => 8.99,
            'img' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2007/12/ricetta-ribollita-semplice/_jcr_content/header-par/image_single.img.jpg/1610368905728.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Torta della Nonna',
            'description' => 'Dolce tradizionale toscano con crema pasticcera, pinoli e scorza di limone.',
            'price' => 7.99,
            'img' => 'https://www.lucake.it/wp-content/uploads/2022/09/torta-della-nonna.jpg',
            'visible' => true,
        ],

        // Ristorante 3
        [
            'restaurant_id' => '3',
            'name' => 'Sushi Misto',
            'description' => 'Assortimento di sushi fresco e variegato, con nigiri, maki e sashimi.',
            'price' => 18.99,
            'img' => 'https://www.wumilano.com/store/wp-content/uploads/2019/07/DSC_98.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Tempura di Gamberi',
            'description' => 'Gamberi avvolti in pastella croccante e fritti, serviti con salsa agrodolce.',
            'price' => 14.99,
            'img' => 'https://i0.wp.com/kungfood.info/wp-content/uploads/2021/10/Piatto-di-tempura-di-gamberi.jpg?ssl=1',
            'visible' => true,
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Sashimi di Salmone',
            'description' => 'Fette di salmone crudo fresco, servite con salsa di soia e zenzero grattugiato.',
            'price' => 16.99,
            'img' => 'https://www.fumara.it/wp-content/uploads/salmone-affumicato-fumara-taglio-sashimi-con-balsamico-igp-e-spuma-di-parmigiano.jpg',
            'visible' => true,
        ],

        // Ristorante 4
        [
            'restaurant_id' => '4',
            'name' => 'Tagliatelle al Ragu',
            'description' => 'Tagliatelle fatte in casa con un ricco sugo di carne cotto lentamente.',
            'price' => 15.99,
            'img' => 'https://www.italianstylecooking.net/wp-content/uploads/2023/07/Tagliatelle-al-ragu.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Lasagne alla Bolognese',
            'description' => 'Strati di pasta all\'uovo alternati a ragù di carne, besciamella e parmigiano, gratinati al forno.',
            'price' => 13.99,
            'img' => 'lasagne.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Torta di Mele',
            'description' => 'Dolce tradizionale emiliano con fette di mela caramellate e pasta frolla croccante.',
            'price' => 6.99,
            'img' => 'https://www.ricettealvolo.it/wp-content/uploads/2023/02/lasagne-bolognese.jpg',
            'visible' => true,
        ],

        // Ristorante 5
        [
            'restaurant_id' => '5',
            'name' => 'Spaghetti ai Frutti di Mare',
            'description' => 'Spaghetti conditi con una selezione di frutti di mare freschi, pomodorini e prezzemolo.',
            'price' => 17.99,
            'img' => 'https://blog.giallozafferano.it/adryincucina/wp-content/uploads/2016/08/linguine-ai-frutti-di-mare.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Cotoletta di Pesce Spada',
            'description' => 'Cotoletta di pesce spada impanata e fritta, servita con spicchi di limone e insalata mista.',
            'price' => 19.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/07/Cotolette-di-pesce-spada-foto-finale-1-1200x675.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Cannoli Siciliani',
            'description' => 'Dolce tipico siciliano con guscio di pasta fritta ripieno di ricotta dolce e scorze d\'arancia candita.',
            'price' => 7.99,
            'img' => 'https://blog.giallozafferano.it/fantasiaincucina/wp-content/uploads/2020/12/Cannolo-siciliano-1.jpg',
            'visible' => true,
        ],
        // Ristorante 6
        [
            'restaurant_id' => '6',
            'name' => 'Riso Cantonese',
            'description' => 'Riso saltato in padella con uova, piselli, gamberetti e salsa di soia.',
            'price' => 11.99,
            'img' => 'https://marsala.gohan-sushi.it/upload/cache/immagini/prodotti/primi_piatti/63_riso_alla_cantonese_2-1920x1187.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Anatra all\'Arancia',
            'description' => 'Piatto tradizionale cinese con anatra arrosto servita con salsa all\'arancia.',
            'price' => 23.99,
            'img' => 'https://media-assets.lacucinaitaliana.it/photos/62908d7a86584f03e6efa9ee/1:1/pass/undefined',
            'visible' => true,
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Gelato al Sesamo Nero',
            'description' => 'Gelato artigianale con aroma di sesamo nero, una delizia fresca e sorprendente.',
            'price' => 5.99,
            'img' => 'https://rende.boasorte.eu/wp-content/uploads/2021/07/DSC04059-scaled.jpg',
            'visible' => true,
        ],

        // Ristorante 7
        [
            'restaurant_id' => '7',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza classica con salsa di pomodoro, mozzarella di bufala DOP e basilico fresco.',
            'price' => 9.99,
            'img' => 'https://www.antoniettapolcaro.it/wp-content/uploads/2023/09/pizza-napoletana-contemporanea-antonietta-polcaro.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Pizza Salamino',
            'description' => 'Pizza con salsa di pomodoro, mozzarella, e salamino piccante.',
            'price' => 11.99,
            'img' => 'https://images.ctfassets.net/n7hs0hadu6ro/1O0Be1dObiQBm17GQJHLj8/3fde720730f0b3616ecf5a82b928e7f9/pizza-a-domicilio-cerca-de-mi.jpg?w=1920&h=1281&fl=progressive&q=50&fm=jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Pizza Capricciosa',
            'description' => 'Pizza con salsa di pomodoro, mozzarella, funghi, prosciutto cotto e carciofini.',
            'price' => 12.99,
            'img' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/04/pizza-capricciosa.jpg',
            'visible' => true,
        ],
        // Ristorante 8
        [
            'restaurant_id' => '8',
            'name' => 'Bistecca alla Griglia',
            'description' => 'Bistecca di manzo alla griglia servita con patate al forno e verdure di stagione.',
            'price' => 24.99,
            'img' => 'https://megastore.bbq4all.it/cdn/shop/articles/bistecca-3.jpg?v=1590168872',
            'visible' => true,
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Insalata Caesar',
            'description' => 'Insalata fresca con crostini di pane, parmigiano grattugiato e salsa Caesar.',
            'price' => 10.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2021/07/Caesar-salad-0D6A0393-1200x675.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Patate al Forno',
            'description' => 'Patate tagliate a spicchi, condite con olio d\'oliva e aromi, cotte al forno fino a doratura.',
            'price' => 6.99,
            'img' => 'https://www.tuorlorosso.it/wp-content/uploads/2021/05/Patate-al-forno-1.jpg',
            'visible' => true,
        ],

        // Ristorante 9
        [
            'restaurant_id' => '9',
            'name' => 'Souvlaki di Pollo',
            'description' => 'Spiedini di pollo marinato e grigliato, serviti con pita e salsa tzatziki.',
            'price' => 13.99,
            'img' => 'https://www.vacanzegreche.com/public/img/data/2020514151650187_souvlaki-grecia1.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Moussaka',
            'description' => 'Piatto greco tradizionale con strati di melanzane, patate, carne macinata e bechamel.',
            'price' => 15.99,
            'img' => 'https://www.mygreekdish.com/wp-content/uploads/2013/05/Moussaka-recipe-Traditional-Greek-Moussaka-with-Eggplants.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Dolmades',
            'description' => 'Foglie di vite ripiene di riso, pinoli e erbe aromatiche, cotte lentamente in salsa di pomodoro.',
            'price' => 11.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2017/06/istock-920393181.jpg',
            'visible' => true,
        ],

        // Ristorante 10
        [
            'restaurant_id' => '10',
            'name' => 'Panino al Pollo',
            'description' => 'Panino con petto di pollo grigliato, lattuga, pomodoro e maionese, servito con patatine fritte.',
            'price' => 8.99,
            'img' => 'https://www.agricolaguidi.com/wp-content/uploads/2020/04/Panino-pollo_0014.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Insalata Greca',
            'description' => 'Insalata fresca con pomodori, cetrioli, olive, cipolla rossa, feta e condimento al limone.',
            'price' => 9.99,
            'img' => 'https://questolhofattoio.agribologna.it/getattachment/d6f9e02c-1893-4ecf-89e3-18fa472eb91a/Insalata-greca.aspx',
            'visible' => true,
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Lasagna al Forno',
            'description' => 'Lasagna tradizionale con pasta fresca, ragù di carne, besciamella e formaggio gratinato.',
            'price' => 12.99,
            'img' => 'https://blog.giallozafferano.it/crisemaxincucina/wp-content/uploads/2018/11/LASAGNE-CLASSICHE-2.jpeg',
            'visible' => true,
        ],
        // Ristorante 11
        [
            'restaurant_id' => '11',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza classica con pomodoro, mozzarella di bufala DOP, basilico e olio extravergine d\'oliva.',
            'price' => 9.99,
            'img' => 'https://www.scattidigusto.it/wp-content/uploads/2018/03/pizza-margherita-originale-Scatti-di-Gusto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Pasta alla Carbonara',
            'description' => 'Pasta lunga condita con uova, guanciale, pecorino romano e pepe nero macinato fresco.',
            'price' => 12.99,
            'img' => 'https://www.buttalapasta.it/wp-content/uploads/2020/04/spaghetti-alla-carbonara.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Tiramisù',
            'description' => 'Dolce italiano classico con strati di savoiardi imbevuti di caffè, crema mascarpone e cacao amaro.',
            'price' => 7.99,
            'img' => 'https://www.cucchiaio.it/content/dam/cucchiaio/it/ricette/2023/08/tiramisu-cremoso/tiramisu-cremoso-finale.jpg',
            'visible' => true,
        ],

        // Ristorante 12
        [
            'restaurant_id' => '12',
            'name' => 'Tortellini in Brodo',
            'description' => 'Tortellini fatti in casa ripieni di carne, serviti in brodo di carne con parmigiano grattugiato.',
            'price' => 11.99,
            'img' => 'https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/010/046/original/tortellini-brodo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '12',
            'name' => 'Tagliatelle al Tartufo',
            'description' => 'Tagliatelle fatte in casa condite con crema di tartufo nero pregiato e scaglie di parmigiano.',
            'price' => 19.99,
            'img' => 'https://www.casapappagallo.it/storage/11554/Spaghetti-al-tartufo-nero.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '12',
            'name' => 'Cotoletta alla Bolognese',
            'description' => 'Cotoletta di maiale impanata e fritta, servita con contorno di patatine fritte e insalata.',
            'price' => 14.99,
            'img' => 'https://www.tortelliniandco.com/wp-content/uploads/2023/04/IMG_7837.jpeg',
            'visible' => true,
        ],

        // Ristorante 13
        [
            'restaurant_id' => '13',
            'name' => 'Sushi Misti',
            'description' => 'Assortimento di sushi fresco, includendo nigiri, sashimi e maki vari.',
            'price' => 22.99,
            'img' => 'https://www.nikkosushi.it/wp-content/uploads/2019/08/74.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '13',
            'name' => 'Tempura di Gamberi',
            'description' => 'Gamberi freschi avvolti in pastella croccante e fritti, serviti con salsa dip.',
            'price' => 15.99,
            'img' => 'https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/tempura-di-gamberi.jpg?itok=-JjFZyK8',
            'visible' => true,
        ],
        [
            'restaurant_id' => '13',
            'name' => 'Sake Nigiri',
            'description' => 'Nigiri di salmone fresco su base di riso condito con aceto di riso.',
            'price' => 8.99,
            'img' => 'sake_nigiri.jpg',
            'visible' => true,
        ],
        // Ristorante 14
        [
            'restaurant_id' => '14',
            'name' => 'Sashimi Misto',
            'description' => 'Assortimento di sashimi freschi, inclusi salmone, tonno e branzino.',
            'price' => 25.99,
            'img' => 'https://roma.boasorte.eu/wp-content/uploads/2021/07/Boa1.png',
            'visible' => true,
        ],
        [
            'restaurant_id' => '14',
            'name' => 'Uramaki California',
            'description' => 'Rotolo di sushi con avocado, surimi, cetriolo e maionese.',
            'price' => 14.99,
            'img' => 'uramaki_california.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '14',
            'name' => 'Gyoza',
            'description' => 'Ravioli giapponesi al vapore ripieni di carne di maiale e verdure.',
            'price' => 9.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/09/Gyoza.jpg',
            'visible' => true,
        ],

        // Ristorante 15
        [
            'restaurant_id' => '15',
            'name' => 'Pizza Napoletana',
            'description' => 'Pizza tradizionale napoletana con pomodoro, mozzarella di bufala DOP, acciughe e olive nere.',
            'price' => 10.99,
            'img' => 'https://media-assets.lacucinaitaliana.it/photos/61fabea083ffd58c524a1ddb/16:9/w_2560%2Cc_limit/pizza-puttanesca.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '15',
            'name' => 'Pasta al Pesto',
            'description' => 'Pasta corta condita con pesto alla genovese, patate e fagiolini.',
            'price' => 11.99,
            'img' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/03/pasta-fredda-al-pesto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '15',
            'name' => 'Cannoli Siciliani',
            'description' => 'Dolce siciliano tradizionale con guscio di pasta fritta ripieno di ricotta dolce e scorza d\'arancia candita.',
            'price' => 8.99,
            'img' => 'https://hazlovegan.com/wp-content/uploads/2021/03/cannoli-siciliani-veganos-8.jpg',
            'visible' => true,
        ],

        // Ristorante 16
        [
            'restaurant_id' => '16',
            'name' => 'Anatra alla Pechinese',
            'description' => 'Anatra arrosto glassata con salsa di soia, miele e spezie, servita con pancake cinesi e cipollotti.',
            'price' => 27.99,
            'img' => 'https://www.buttalapasta.it/wp-content/uploads/2021/02/anatra-alla-pechinese.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '16',
            'name' => 'Pollo alle Mandorle',
            'description' => 'Pollo fritto croccante con salsa agrodolce alle mandorle, servito con riso basmati.',
            'price' => 18.99,
            'img' => 'https://media-assets.lacucinaitaliana.it/photos/61fa71d9ace1ad5f106d7903/16:9/w_2560%2Cc_limit/2_pollo-alle-mandorle.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '16',
            'name' => 'Gamberi in Salsa Piccante',
            'description' => 'Gamberi saltati in padella con peperoncino fresco, aglio, zenzero e salsa piccante, serviti con verdure croccanti.',
            'price' => 22.99,
            'img' => 'https://www.ristorante-giapponese.it/wp-content/uploads/2020/06/249.png',
            'visible' => true,
        ],
        // Ristorante 17
        [
            'restaurant_id' => '17',
            'name' => 'Tacos al Pastor',
            'description' => 'Tacos di maiale marinato con ananas, cipolla e coriandolo, serviti con salsa piccante.',
            'price' => 12.99,
            'img' => 'https://iamafoodblog.b-cdn.net/wp-content/uploads/2021/05/al-pastor-3507w.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '17',
            'name' => 'Burrito Carnitas',
            'description' => 'Burrito ripieno di carne di maiale alla carnitas, riso, fagioli, formaggio e guacamole.',
            'price' => 14.99,
            'img' => 'https://twodollareats.com/wp-content/uploads/2019/10/Two-Dollar-Eats-4476-1300x867.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '17',
            'name' => 'Margarita alla Fragola',
            'description' => 'Cocktail classico con tequila, triple sec, succo di lime e purea di fragole.',
            'price' => 9.99,
            'img' => 'https://www.ricettasprint.it/wp-content/uploads/2020/08/Drink-fragola-e-basilico-FOTO-ricettasprint-3.jpg',
            'visible' => true,
        ],

        // Ristorante 18
        [
            'restaurant_id' => '18',
            'name' => 'Sushi Sashimi Combo',
            'description' => 'Assortimento di sushi e sashimi misti freschi e prelibati.',
            'price' => 29.99,
            'img' => 'https://images.squarespace-cdn.com/content/v1/51d3a842e4b0d2448ac01e8d/cad0d366-f2a5-4f44-bbac-a081bf3a9e26/DeluxeSushiCombo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '18',
            'name' => 'Tempura Misto',
            'description' => 'Assortimento di tempura croccante di gamberi, verdure e pesce.',
            'price' => 18.99,
            'img' => 'https://www.ricettasprint.it/wp-content/uploads/2017/04/iStock-497180612-1280x720.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '18',
            'name' => 'Ramen Tonkotsu',
            'description' => 'Zuppa giapponese di ramen con brodo di maiale cremoso, tagliatelle, maiale brasato, uovo sodo, alga nori e cipollotti.',
            'price' => 16.99,
            'img' => 'https://www.foodandwine.com/thmb/0AXGLeY6dYnY8sEXFqxBa8opDrs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Tonkotsu-Ramen-FT-BLOG1122-8fe6c12d609a4fd4ab246bea3aae140e.jpg',
            'visible' => true,
        ],

        // Ristorante 19
        [
            'restaurant_id' => '19',
            'name' => 'Pollo Tikka Masala',
            'description' => 'Pollo marinato in una salsa cremosa di pomodoro e curry speziato, servito con riso basmati.',
            'price' => 17.99,
            'img' => 'https://images.dissapore.com/wp-content/uploads/2023/03/pollo-tikka-masala-ricetta.jpg?width=1280&height=720&quality=75',
            'visible' => true,
        ],
        [
            'restaurant_id' => '19',
            'name' => 'Biryani di Agnello',
            'description' => 'Riso basmati cucinato con agnello speziato, uova sode, cipolle caramellate e una selezione di spezie.',
            'price' => 19.99,
            'img' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5XcGglASNXMJlNQy145dZMx4sdeXXe5Ycyw&usqp=CAU',
            'visible' => true,
        ],
        [
            'restaurant_id' => '19',
            'name' => 'Naan all\'Aglio',
            'description' => 'Pane indiano naan cotto in forno tandoor con burro e aglio.',
            'price' => 5.99,
            'img' => 'https://recipecontent.fooby.ch/21239_3-2_1920-1280.jpg',
            'visible' => true,
        ],

        // Ristorante 20
        [
            'restaurant_id' => '20',
            'name' => 'Insalata Greca',
            'description' => 'Insalata fresca con pomodori, cetrioli, olive, cipolla rossa, feta, peperoncini e condimento al limone e olio d\'oliva.',
            'price' => 12.99,
            'img' => 'https://blog.giallozafferano.it/studentiaifornelli/wp-content/uploads/2017/08/2020-insalata-greca-con-feta-ricetta-insalata-con-pomodori-cetrioli-cipolle.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '20',
            'name' => 'Lasagne Vegetariane',
            'description' => 'Lasagne fatte in casa con strati di pasta, besciamella, pomodoro, melanzane, zucchine e formaggio.',
            'price' => 14.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2018/06/lasagne_vegetariane_-3.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '20',
            'name' => 'Torta di Carote',
            'description' => 'Torta soffice e umida con carote grattugiate, noci e una spolverata di cannella.',
            'price' => 8.99,
            'img' => 'https://www.lucake.it/wp-content/uploads/2022/10/torta-di-carote.jpg',
            'visible' => true,
        ],
        // Ristorante 21
        [
            'restaurant_id' => '21',
            'name' => 'Anatra alla Pechinese',
            'description' => 'Anatra arrosto con crosta croccante, servita con salsa alla prugna e verdure saltate.',
            'price' => 24.99,
            'img' => 'https://images.rove.me/w_1920,q_85/zhieisvkt7eu3bmfw6bo/beijing-peking-duck.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '21',
            'name' => 'Gamberi in Salsa Agrodolce',
            'description' => 'Gamberi fritti in pastella croccante, ricoperti di salsa agrodolce e sesamo.',
            'price' => 18.99,
            'img' => 'https://www.ristorantedong.it/wp-content/uploads/Ristorante-Dong-Menu-WEB-177.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '21',
            'name' => 'Riso Cantonese',
            'description' => 'Riso saltato con uova, piselli, carote, gamberetti e salsa di soia.',
            'price' => 15.99,
            'img' => 'https://lh3.googleusercontent.com/proxy/ZUE9PS4nLxSqRXmB5kOpiYqwE2KDn6VuFIGeyTt67UBVVxIksdf9VjEvLKoi-8KQcrJusiFw6yPE5pqtJTkHOJBgKuA2SUT8AP5aUyXhHhTbTHZr',
            'visible' => true,
        ],

        // Ristorante 22
        [
            'restaurant_id' => '22',
            'name' => 'Whopper Burger',
            'description' => 'Hamburger alla griglia con carne 100% manzo, formaggio, lattuga, pomodoro, cipolla e maionese.',
            'price' => 11.99,
            'img' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM-X0RG7rg5V6dnkCbYZiln8IyCX6DAsr3HQ&usqp=CAU',
            'visible' => true,
        ],
        [
            'restaurant_id' => '22',
            'name' => 'Chicken Royale',
            'description' => 'Panino con petto di pollo alla griglia, formaggio, lattuga, maionese e ketchup.',
            'price' => 9.99,
            'img' => 'https://metro.co.uk/wp-content/uploads/2023/06/SEC_159128747-bbfb.jpg?quality=90&strip=all',
            'visible' => true,
        ],
        [
            'restaurant_id' => '22',
            'name' => 'Onion Rings',
            'description' => 'Anelli di cipolla impanati e fritti, serviti con salsa barbecue.',
            'price' => 6.99,
            'img' => 'https://kristineskitchenblog.com/wp-content/uploads/2022/03/crispy-air-fryer-onion-rings-recipe-0775.jpg',
            'visible' => true,
        ],

        // Ristorante 23
        [
            'restaurant_id' => '23',
            'name' => 'Fajitas di Pollo',
            'description' => 'Strisce di pollo alla griglia con peperoni, cipolle e condimenti, servite con tortillas calde.',
            'price' => 16.99,
            'img' => 'https://www.casapappagallo.it/storage/2510/fajitas-di-pollo.JPG',
            'visible' => true,
        ],
        [
            'restaurant_id' => '23',
            'name' => 'Burrito di Manzo',
            'description' => 'Burrito ripieno di manzo alla griglia, riso, fagioli, formaggio e salsa al peperoncino.',
            'price' => 14.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/05/Burrito-0D6A3943.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '23',
            'name' => 'Margarita al Mango',
            'description' => 'Cocktail rinfrescante con tequila, triple sec, succo di lime e purea di mango.',
            'price' => 10.99,
            'img' => 'https://static.vecteezy.com/ti/foto-gratuito/p2/24215803-cocktail-margarita-congelati-al-mango-foto.jpg',
            'visible' => true,
        ],

        // Ristorante 24
        [
            'restaurant_id' => '24',
            'name' => 'Asado Argentino',
            'description' => 'Assortimento di carni alla griglia tra cui salsicce, costine e bistecca, servito con chimichurri.',
            'price' => 29.99,
            'img' => 'https://marchesestore.it/cdn/shop/articles/come-cucinare-lasado-argentino-consigli-per-un-piatto-unico.webp?v=1697419652',
            'visible' => true,
        ],
        [
            'restaurant_id' => '24',
            'name' => 'Empanadas di Carne',
            'description' => 'Fagottini di pasta sfoglia ripieni di carne tritata, olive, uova sode e spezie.',
            'price' => 12.99,
            'img' => 'https://www.repstatic.it/content/nazionale/img/2021/03/08/063911933-dd38aff7-bfca-4e1b-9553-f105e78f79fb.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '24',
            'name' => 'Milanesa alla Napolitana',
            'description' => 'Cotoletta di carne di manzo impanata, fritta e gratinata al forno con salsa di pomodoro e mozzarella.',
            'price' => 18.99,
            'img' => 'https://i0.wp.com/www.vivilargentina.com/wp-content/uploads/2014/11/maxresdefault.jpg',
            'visible' => true,
        ],

        // Ristorante 25
        [
            'restaurant_id' => '25',
            'name' => 'Pollo al Curry',
            'description' => 'Pollo cucinato in una salsa di curry cremosa con peperoni, cipolle e spezie.',
            'price' => 17.99,
            'img' => 'https://www.vivilight.it/wp-content/uploads/2020/05/Pollo-al-curry-light-%E2%80%93-Ricetta-asiatica-veloce-2000x1362.png',
            'visible' => true,
        ],
        [
            'restaurant_id' => '25',
            'name' => 'Pane Naan',
            'description' => 'Pane indiano soffice cotto in forno tandoor, ideale per accompagnare piatti speziati.',
            'price' => 5.99,
            'img' => 'https://i0.wp.com/paneamoreceliachia.it/wp-content/uploads/2021/02/Pane-Naan-allo-yogurt-senza-glutine-Paneamoreceliachia-sl.jpg?fit=1390%2C869&ssl=1',
            'visible' => true,
        ],
        [
            'restaurant_id' => '25',
            'name' => 'Gulab Jamun',
            'description' => 'Dolce indiano a base di latte condensato e farina, fritto e immerso in sciroppo di zucchero.',
            'price' => 8.99,
            'img' => 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Gulab_jamun_%28Gibraltar%2C_November_2020%29.jpg',
            'visible' => true,
        ],

        // Ristorante 26
        [
            'restaurant_id' => '26',
            'name' => 'Bistecca alla Fiorentina',
            'description' => 'Taglio di bistecca di manzo alla griglia, servito con patate al rosmarino e verdure di stagione.',
            'price' => 35.99,
            'img' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2018/08/bistecca-alla-fiorentina.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '26',
            'name' => 'Pasta alla Norma',
            'description' => 'Pasta con pomodori, melanzane fritte, basilico e ricotta salata, un classico della cucina siciliana.',
            'price' => 14.99,
            'img' => 'https://www.casapappagallo.it/storage/21564/pasta-alla-norma.JPG',
            'visible' => true,
        ],
        [
            'restaurant_id' => '26',
            'name' => 'Cannoli Siciliani',
            'description' => 'Dolce siciliano a base di pasta fritta ripiena di ricotta dolce, cioccolato e scorza d\'arancia.',
            'price' => 9.99,
            'img' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2017/03/anteprima-14-scaled.jpg',
            'visible' => true,
        ],

        // Ristorante 27
        [
            'restaurant_id' => '27',
            'name' => 'Sashimi Misto',
            'description' => 'Assortimento di pesce crudo fresco, tagliato sottile e servito con salsa di soia e wasabi.',
            'price' => 22.99,
            'img' => 'https://www.ristorantedong.it/wp-content/uploads/Ristorante-Dong-Menu-WEB-54.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '27',
            'name' => 'Yakitori di Pollo',
            'description' => 'Spiedini di pollo grigliati e glassati con salsa teriyaki, serviti con riso al vapore.',
            'price' => 16.99,
            'img' => 'https://www.corriere.it/methode_image/2023/07/06/Cucina/Foto%20Cucina%20-%20Trattate/Yakitori%20di%20pollo-397-kjzF-U34202231276633hKI-1124x631@Corriere-Web-Sezioni.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '27',
            'name' => 'Tempura di Gamberi',
            'description' => 'Gamberi freschi immersi in pastella leggera e fritti fino a doratura, serviti con salsa di immersione.',
            'price' => 18.99,
            'img' => 'https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/tempura-di-gamberi.jpg?itok=-JjFZyK8',
            'visible' => true,
        ],

        // Ristorante 28
        [
            'restaurant_id' => '28',
            'name' => 'Ribollita Toscana',
            'description' => 'Zuppa toscana tradizionale con verdure di stagione, pane raffermo e fagioli cannellini.',
            'price' => 12.99,
            'img' => 'https://passioneperlatavola.it/wp-content/uploads/2021/11/ribollita-toscana-0-scaled.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '28',
            'name' => 'Tagliata di Manzo',
            'description' => 'Trancio di manzo alla griglia servito su un letto di rucola e scaglie di Parmigiano Reggiano.',
            'price' => 26.99,
            'img' => 'https://www.wineandfoodtour.it/wp-content/uploads/2023/08/Come-cucinare-una-tagliata-di-manzo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '28',
            'name' => 'Tiramisù Tradizionale',
            'description' => 'Dolce italiano composto da savoiardi inzuppati nel caffè, crema al mascarpone e cacao amaro.',
            'price' => 8.99,
            'img' => 'https://blog.giallozafferano.it/lebistro/wp-content/uploads/2018/12/tiramisu%CC%80.jpg',
            'visible' => true,
        ],

        // Ristorante 29
        [
            'restaurant_id' => '29',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza classica con pomodoro, mozzarella e basilico fresco.',
            'price' => 10.99,
            'img' => 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Pizza_Margherita_stu_spivack.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '29',
            'name' => 'Spaghetti Carbonara',
            'description' => 'Pasta con pancetta croccante, uova, pecorino e pepe nero.',
            'price' => 14.99,
            'img' => 'https://www.chompslurrpburp.com/wp-content/uploads/2021/12/spaghetti-carbonara.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '29',
            'name' => 'Torta della Nonna',
            'description' => 'Torta rustica con crema pasticcera, pinoli e scorza di limone, coperta di zucchero a velo.',
            'price' => 7.99,
            'img' => 'https://www.thespruceeats.com/thmb/rdwFw3KajYxXIidcuqGN-eRGR0M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ahIMG_5346fhor-a02b6074d4524c898d1f9eeb91536e68.jpg',
            'visible' => true,
        ],

        // Ristorante 30
        [
            'restaurant_id' => '30',
            'name' => 'Sushi Sashimi Combo',
            'description' => 'Assortimento di sushi e sashimi freschi, accompagnati da riso e salsa di soia.',
            'price' => 32.99,
            'img' => 'https://i.redd.it/auzehrt47mo01.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '30',
            'name' => 'Uramaki California Roll',
            'description' => 'Rotolo di sushi con gamberetti, avocado, cetriolo e maionese, ricoperto di sesamo.',
            'price' => 18.99,
            'img' => 'https://www.sidechef.com/recipe/8f379697-7d39-4f61-a336-fd4134eeee18.jpg?d=1408x1120',
            'visible' => true,
        ],
        [
            'restaurant_id' => '30',
            'name' => 'Miso Soup',
            'description' => 'Zuppa giapponese leggera e salata a base di brodo di miso, alghe e tofu.',
            'price' => 5.99,
            'img' => 'https://www.crowdedkitchen.com/wp-content/uploads/2020/08/vegan-miso-soup.jpg',
            'visible' => true,
        ],

        // Ristorante 31
        [
            'restaurant_id' => '31',
            'name' => 'Pad Thai Gamberi',
            'description' => 'Noodle di riso saltati con gamberi freschi, uova, cipolle, germogli di soia e arachidi.',
            'price' => 16.99,
            'img' => 'https://www.checucino.it/wp-content/uploads/2022/03/pad-thai.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '31',
            'name' => 'Gyoza di Verdure',
            'description' => 'Ravioli giapponesi fritti ripieni di verdure tritate e aromi orientali, serviti con salsa ponzu.',
            'price' => 12.99,
            'img' => 'https://www.ginkosushi.it/wp-content/uploads/2021/12/img_0628-scaled.jpeg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '31',
            'name' => 'Sake Nigiri',
            'description' => 'Salmone fresco su cuscino di riso delicatamente condito, accompagnato da wasabi e zenzero.',
            'price' => 9.99,
            'img' => 'https://okasan.it/tablet/wp-content/uploads/2017/02/01-nigiri-salmone_new.jpg',
            'visible' => true,
        ],
    ];
