<?php
return

    [
        // Ristorante 1
        [
            'restaurant_id' => '1',
            'name' => 'Pasta alla Carbonara',
            'description' => 'La classica pasta italiana con uova, pancetta, formaggio e pepe nero.',
            'price' => 12.99,
            'img' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/11/ricetta-spaghetti-carbonara/_jcr_content/header-par/image_single.img.jpg/1617198167116.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza con pomodoro, mozzarella di bufala, basilico fresco e olio d\'oliva.',
            'price' => 9.99,
            'img' => 'https://www.lemilleeunabontadifranci.it/wp-content/uploads/2021/04/Pizza-margherita-fatta-in-casa-orizzontale.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Tiramisù',
            'description' => 'Dolce italiano composto da savoiardi inzuppati nel caffè, crema di mascarpone e cacao amaro.',
            'price' => 6.99,
            'img' => 'tiramisu.jpg',
            'visible' => true,
        ],

        // Ristorante 2
        [
            'restaurant_id' => '2',
            'name' => 'Bistecca alla Fiorentina',
            'description' => 'Fiorentina di manzo grigliata, servita al sangue e condita con sale grosso e olio d\'oliva.',
            'price' => 25.99,
            'img' => 'fiorentina.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Ribollita',
            'description' => 'Zuppa toscana a base di pane raffermo, verdure miste, fagioli e cavolo nero.',
            'price' => 8.99,
            'img' => 'ribollita.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Torta della Nonna',
            'description' => 'Dolce tradizionale toscano con crema pasticcera, pinoli e scorza di limone.',
            'price' => 7.99,
            'img' => 'torta_nonna.jpg',
            'visible' => true,
        ],

        // Ristorante 3
        [
            'restaurant_id' => '3',
            'name' => 'Sushi Misto',
            'description' => 'Assortimento di sushi fresco e variegato, con nigiri, maki e sashimi.',
            'price' => 18.99,
            'img' => 'sushi_misto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Tempura di Gamberi',
            'description' => 'Gamberi avvolti in pastella croccante e fritti, serviti con salsa agrodolce.',
            'price' => 14.99,
            'img' => 'tempura_gamberi.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Sashimi di Salmone',
            'description' => 'Fette di salmone crudo fresco, servite con salsa di soia e zenzero grattugiato.',
            'price' => 16.99,
            'img' => 'sashimi_salmone.jpg',
            'visible' => true,
        ],

        // Ristorante 4
        [
            'restaurant_id' => '4',
            'name' => 'Tagliatelle al Ragu',
            'description' => 'Tagliatelle fatte in casa con un ricco sugo di carne cotto lentamente.',
            'price' => 15.99,
            'img' => 'tagliatelle.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Lasagne alla Bolognese',
            'description' => 'Strati di pasta all\'uovo alternati a ragù di carne, besciamella e parmigiano, gratinati al forno.',
            'price' => 13.99,
            'img' => 'lasagne.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Torta di Mele',
            'description' => 'Dolce tradizionale emiliano con fette di mela caramellate e pasta frolla croccante.',
            'price' => 6.99,
            'img' => 'torta_mele.jpg',
            'visible' => true,
        ],

        // Ristorante 5
        [
            'restaurant_id' => '5',
            'name' => 'Spaghetti ai Frutti di Mare',
            'description' => 'Spaghetti conditi con una selezione di frutti di mare freschi, pomodorini e prezzemolo.',
            'price' => 17.99,
            'img' => 'spaghetti_frutti_di_mare.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Cotoletta di Pesce Spada',
            'description' => 'Cotoletta di pesce spada impanata e fritta, servita con spicchi di limone e insalata mista.',
            'price' => 19.99,
            'img' => 'cotoletta_pesce_spada.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Cannoli Siciliani',
            'description' => 'Dolce tipico siciliano con guscio di pasta fritta ripieno di ricotta dolce e scorze d\'arancia candita.',
            'price' => 7.99,
            'img' => 'cannoli.jpg',
            'visible' => true,
        ],
        // Ristorante 6
        [
            'restaurant_id' => '6',
            'name' => 'Riso Cantonese',
            'description' => 'Riso saltato in padella con uova, piselli, gamberetti e salsa di soia.',
            'price' => 11.99,
            'img' => 'riso_cantonese.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Anatra all\'Arancia',
            'description' => 'Piatto tradizionale cinese con anatra arrosto servita con salsa all\'arancia.',
            'price' => 23.99,
            'img' => 'anatra_arancia.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Gelato al Sesamo Nero',
            'description' => 'Gelato artigianale con aroma di sesamo nero, una delizia fresca e sorprendente.',
            'price' => 5.99,
            'img' => 'gelato_sesamo.jpg',
            'visible' => true,
        ],

        // Ristorante 7
        [
            'restaurant_id' => '7',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza classica con salsa di pomodoro, mozzarella di bufala DOP e basilico fresco.',
            'price' => 9.99,
            'img' => 'pizza_margherita.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Pizza Pepperoni',
            'description' => 'Pizza con salsa di pomodoro, mozzarella, e peperoni piccanti.',
            'price' => 11.99,
            'img' => 'pizza_pepperoni.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Pizza Capricciosa',
            'description' => 'Pizza con salsa di pomodoro, mozzarella, funghi, prosciutto cotto e carciofini.',
            'price' => 12.99,
            'img' => 'pizza_capricciosa.jpg',
            'visible' => true,
        ],
        // Ristorante 8
        [
            'restaurant_id' => '8',
            'name' => 'Bistecca alla Griglia',
            'description' => 'Bistecca di manzo alla griglia servita con patate al forno e verdure di stagione.',
            'price' => 24.99,
            'img' => 'bistecca_griglia.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Insalata Caesar',
            'description' => 'Insalata fresca con crostini di pane, parmigiano grattugiato e salsa Caesar.',
            'price' => 10.99,
            'img' => 'insalata_caesar.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Patate al Forno',
            'description' => 'Patate tagliate a spicchi, condite con olio d\'oliva e aromi, cotte al forno fino a doratura.',
            'price' => 6.99,
            'img' => 'patate_forno.jpg',
            'visible' => true,
        ],

        // Ristorante 9
        [
            'restaurant_id' => '9',
            'name' => 'Souvlaki di Pollo',
            'description' => 'Spiedini di pollo marinato e grigliato, serviti con pita e salsa tzatziki.',
            'price' => 13.99,
            'img' => 'souvlaki_pollo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Moussaka',
            'description' => 'Piatto greco tradizionale con strati di melanzane, patate, carne macinata e bechamel.',
            'price' => 15.99,
            'img' => 'moussaka.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Dolmades',
            'description' => 'Foglie di vite ripiene di riso, pinoli e erbe aromatiche, cotte lentamente in salsa di pomodoro.',
            'price' => 11.99,
            'img' => 'dolmades.jpg',
            'visible' => true,
        ],

        // Ristorante 10
        [
            'restaurant_id' => '10',
            'name' => 'Panino al Pollo',
            'description' => 'Panino con petto di pollo grigliato, lattuga, pomodoro e maionese, servito con patatine fritte.',
            'price' => 8.99,
            'img' => 'panino_pollo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Insalata Greca',
            'description' => 'Insalata fresca con pomodori, cetrioli, olive, cipolla rossa, feta e condimento al limone.',
            'price' => 9.99,
            'img' => 'insalata_greca.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Lasagna al Forno',
            'description' => 'Lasagna tradizionale con pasta fresca, ragù di carne, besciamella e formaggio gratinato.',
            'price' => 12.99,
            'img' => 'lasagna.jpg',
            'visible' => true,
        ],
        // Ristorante 11
        [
            'restaurant_id' => '11',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza classica con pomodoro, mozzarella di bufala DOP, basilico e olio extravergine d\'oliva.',
            'price' => 9.99,
            'img' => 'pizza_margherita.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Pasta alla Carbonara',
            'description' => 'Pasta lunga condita con uova, guanciale, pecorino romano e pepe nero macinato fresco.',
            'price' => 12.99,
            'img' => 'carbonara.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Tiramisù',
            'description' => 'Dolce italiano classico con strati di savoiardi imbevuti di caffè, crema mascarpone e cacao amaro.',
            'price' => 7.99,
            'img' => 'tiramisu.jpg',
            'visible' => true,
        ],

        // Ristorante 12
        [
            'restaurant_id' => '12',
            'name' => 'Tortellini in Brodo',
            'description' => 'Tortellini fatti in casa ripieni di carne, serviti in brodo di carne con parmigiano grattugiato.',
            'price' => 11.99,
            'img' => 'tortellini_brodo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '12',
            'name' => 'Tagliatelle al Tartufo',
            'description' => 'Tagliatelle fatte in casa condite con crema di tartufo nero pregiato e scaglie di parmigiano.',
            'price' => 19.99,
            'img' => 'tagliatelle_tartufo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '12',
            'name' => 'Cotoletta alla Bolognese',
            'description' => 'Cotoletta di maiale impanata e fritta, servita con contorno di patatine fritte e insalata.',
            'price' => 14.99,
            'img' => 'cotoletta.jpg',
            'visible' => true,
        ],

        // Ristorante 13
        [
            'restaurant_id' => '13',
            'name' => 'Sushi Misti',
            'description' => 'Assortimento di sushi fresco, includendo nigiri, sashimi e maki vari.',
            'price' => 22.99,
            'img' => 'sushi_misti.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '13',
            'name' => 'Tempura di Gamberi',
            'description' => 'Gamberi freschi avvolti in pastella croccante e fritti, serviti con salsa dip.',
            'price' => 15.99,
            'img' => 'tempura_gamberi.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '13',
            'name' => 'Sake Nigiri',
            'description' => 'Nigiri di salmone fresco su base di riso condito con aceto di riso.',
            'price' => 8.99,
            'img' => 'sake_nigiri.jpg',
            'visible' => true,
        ],
        // Ristorante 14
        [
            'restaurant_id' => '14',
            'name' => 'Sashimi Misto',
            'description' => 'Assortimento di sashimi freschi, inclusi salmone, tonno e branzino.',
            'price' => 25.99,
            'img' => 'sashimi_misto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '14',
            'name' => 'Uramaki California',
            'description' => 'Rotolo di sushi con avocado, surimi, cetriolo e maionese.',
            'price' => 14.99,
            'img' => 'uramaki_california.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '14',
            'name' => 'Gyoza',
            'description' => 'Ravioli giapponesi al vapore ripieni di carne di maiale e verdure.',
            'price' => 9.99,
            'img' => 'gyoza.jpg',
            'visible' => true,
        ],

        // Ristorante 15
        [
            'restaurant_id' => '15',
            'name' => 'Pizza Napoletana',
            'description' => 'Pizza tradizionale napoletana con pomodoro, mozzarella di bufala DOP, acciughe e olive nere.',
            'price' => 10.99,
            'img' => 'pizza_napoletana.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '15',
            'name' => 'Pasta al Pesto',
            'description' => 'Pasta corta condita con pesto alla genovese, patate e fagiolini.',
            'price' => 11.99,
            'img' => 'pasta_pesto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '15',
            'name' => 'Cannoli Siciliani',
            'description' => 'Dolce siciliano tradizionale con guscio di pasta fritta ripieno di ricotta dolce e scorza d\'arancia candita.',
            'price' => 8.99,
            'img' => 'cannoli_siciliani.jpg',
            'visible' => true,
        ],

        // Ristorante 16
        [
            'restaurant_id' => '16',
            'name' => 'Anatra alla Pechinese',
            'description' => 'Anatra arrosto glassata con salsa di soia, miele e spezie, servita con pancake cinesi e cipollotti.',
            'price' => 27.99,
            'img' => 'anatra_pechinese.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '16',
            'name' => 'Pollo alle Mandorle',
            'description' => 'Pollo fritto croccante con salsa agrodolce alle mandorle, servito con riso basmati.',
            'price' => 18.99,
            'img' => 'pollo_mandorle.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '16',
            'name' => 'Gamberi in Salsa Piccante',
            'description' => 'Gamberi saltati in padella con peperoncino fresco, aglio, zenzero e salsa piccante, serviti con verdure croccanti.',
            'price' => 22.99,
            'img' => 'gamberi_salsa_piccante.jpg',
            'visible' => true,
        ],
        // Ristorante 17
        [
            'restaurant_id' => '17',
            'name' => 'Tacos al Pastor',
            'description' => 'Tacos di maiale marinato con ananas, cipolla e coriandolo, serviti con salsa piccante.',
            'price' => 12.99,
            'img' => 'tacos_al_pastor.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '17',
            'name' => 'Burrito Carnitas',
            'description' => 'Burrito ripieno di carne di maiale alla carnitas, riso, fagioli, formaggio e guacamole.',
            'price' => 14.99,
            'img' => 'burrito_carnitas.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '17',
            'name' => 'Margarita alla Fragola',
            'description' => 'Cocktail classico con tequila, triple sec, succo di lime e purea di fragole.',
            'price' => 9.99,
            'img' => 'margarita_fragola.jpg',
            'visible' => true,
        ],

        // Ristorante 18
        [
            'restaurant_id' => '18',
            'name' => 'Sushi Sashimi Combo',
            'description' => 'Assortimento di sushi e sashimi misti freschi e prelibati.',
            'price' => 29.99,
            'img' => 'sushi_sashimi_combo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '18',
            'name' => 'Tempura Misto',
            'description' => 'Assortimento di tempura croccante di gamberi, verdure e pesce.',
            'price' => 18.99,
            'img' => 'tempura_misto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '18',
            'name' => 'Ramen Tonkotsu',
            'description' => 'Zuppa giapponese di ramen con brodo di maiale cremoso, tagliatelle, maiale brasato, uovo sodo, alga nori e cipollotti.',
            'price' => 16.99,
            'img' => 'ramen_tonkotsu.jpg',
            'visible' => true,
        ],

        // Ristorante 19
        [
            'restaurant_id' => '19',
            'name' => 'Pollo Tikka Masala',
            'description' => 'Pollo marinato in una salsa cremosa di pomodoro e curry speziato, servito con riso basmati.',
            'price' => 17.99,
            'img' => 'pollo_tikka_masala.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '19',
            'name' => 'Biryani di Agnello',
            'description' => 'Riso basmati cucinato con agnello speziato, uova sode, cipolle caramellate e una selezione di spezie.',
            'price' => 19.99,
            'img' => 'biryani_agnello.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '19',
            'name' => 'Naan all\'Aglio',
            'description' => 'Pane indiano naan cotto in forno tandoor con burro e aglio.',
            'price' => 5.99,
            'img' => 'naan_aglio.jpg',
            'visible' => true,
        ],

        // Ristorante 20
        [
            'restaurant_id' => '20',
            'name' => 'Insalata Greca',
            'description' => 'Insalata fresca con pomodori, cetrioli, olive, cipolla rossa, feta, peperoncini e condimento al limone e olio d\'oliva.',
            'price' => 12.99,
            'img' => 'insalata_greca.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '20',
            'name' => 'Lasagne Vegetariane',
            'description' => 'Lasagne fatte in casa con strati di pasta, besciamella, pomodoro, melanzane, zucchine e formaggio.',
            'price' => 14.99,
            'img' => 'lasagne_vegetariane.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '20',
            'name' => 'Torta di Carote',
            'description' => 'Torta soffice e umida con carote grattugiate, noci e una spolverata di cannella.',
            'price' => 8.99,
            'img' => 'torta_carote.jpg',
            'visible' => true,
        ],
        // Ristorante 21
        [
            'restaurant_id' => '21',
            'name' => 'Anatra alla Pechinese',
            'description' => 'Anatra arrosto con crosta croccante, servita con salsa alla prugna e verdure saltate.',
            'price' => 24.99,
            'img' => 'anatra_pechinese.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '21',
            'name' => 'Gamberi in Salsa Agrodolce',
            'description' => 'Gamberi fritti in pastella croccante, ricoperti di salsa agrodolce e sesamo.',
            'price' => 18.99,
            'img' => 'gamberi_salsa_agrodolce.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '21',
            'name' => 'Riso Cantonese',
            'description' => 'Riso saltato con uova, piselli, carote, gamberetti e salsa di soia.',
            'price' => 15.99,
            'img' => 'riso_cantonese.jpg',
            'visible' => true,
        ],

        // Ristorante 22
        [
            'restaurant_id' => '22',
            'name' => 'Whopper Burger',
            'description' => 'Hamburger alla griglia con carne 100% manzo, formaggio, lattuga, pomodoro, cipolla e maionese.',
            'price' => 11.99,
            'img' => 'whopper_burger.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '22',
            'name' => 'Chicken Royale',
            'description' => 'Panino con petto di pollo alla griglia, formaggio, lattuga, maionese e ketchup.',
            'price' => 9.99,
            'img' => 'chicken_royale.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '22',
            'name' => 'Onion Rings',
            'description' => 'Anelli di cipolla impanati e fritti, serviti con salsa barbecue.',
            'price' => 6.99,
            'img' => 'onion_rings.jpg',
            'visible' => true,
        ],

        // Ristorante 23
        [
            'restaurant_id' => '23',
            'name' => 'Fajitas di Pollo',
            'description' => 'Strisce di pollo alla griglia con peperoni, cipolle e condimenti, servite con tortillas calde.',
            'price' => 16.99,
            'img' => 'fajitas_pollo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '23',
            'name' => 'Burrito di Manzo',
            'description' => 'Burrito ripieno di manzo alla griglia, riso, fagioli, formaggio e salsa al peperoncino.',
            'price' => 14.99,
            'img' => 'burrito_manzo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '23',
            'name' => 'Margarita al Mango',
            'description' => 'Cocktail rinfrescante con tequila, triple sec, succo di lime e purea di mango.',
            'price' => 10.99,
            'img' => 'margarita_mango.jpg',
            'visible' => true,
        ],

        // Ristorante 24
        [
            'restaurant_id' => '24',
            'name' => 'Asado Argentino',
            'description' => 'Assortimento di carni alla griglia tra cui salsicce, costine e bistecca, servito con chimichurri.',
            'price' => 29.99,
            'img' => 'asado_argentino.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '24',
            'name' => 'Empanadas di Carne',
            'description' => 'Fagottini di pasta sfoglia ripieni di carne tritata, olive, uova sode e spezie.',
            'price' => 12.99,
            'img' => 'empanadas_carne.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '24',
            'name' => 'Milanesa alla Napolitana',
            'description' => 'Cotoletta di carne di manzo impanata, fritta e gratinata al forno con salsa di pomodoro e mozzarella.',
            'price' => 18.99,
            'img' => 'milanesa_napolitana.jpg',
            'visible' => true,
        ],

        // Ristorante 25
        [
            'restaurant_id' => '25',
            'name' => 'Pollo al Curry',
            'description' => 'Pollo cucinato in una salsa di curry cremosa con peperoni, cipolle e spezie.',
            'price' => 17.99,
            'img' => 'pollo_curry.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '25',
            'name' => 'Pane Naan',
            'description' => 'Pane indiano soffice cotto in forno tandoor, ideale per accompagnare piatti speziati.',
            'price' => 5.99,
            'img' => 'pane_naan.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '25',
            'name' => 'Gulab Jamun',
            'description' => 'Dolce indiano a base di latte condensato e farina, fritto e immerso in sciroppo di zucchero.',
            'price' => 8.99,
            'img' => 'gulab_jamun.jpg',
            'visible' => true,
        ],

        // Ristorante 26
        [
            'restaurant_id' => '26',
            'name' => 'Bistecca alla Fiorentina',
            'description' => 'Taglio di bistecca di manzo alla griglia, servito con patate al rosmarino e verdure di stagione.',
            'price' => 35.99,
            'img' => 'bistecca_fiorentina.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '26',
            'name' => 'Pasta alla Norma',
            'description' => 'Pasta con pomodori, melanzane fritte, basilico e ricotta salata, un classico della cucina siciliana.',
            'price' => 14.99,
            'img' => 'pasta_norma.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '26',
            'name' => 'Cannoli Siciliani',
            'description' => 'Dolce siciliano a base di pasta fritta ripiena di ricotta dolce, cioccolato e scorza d\'arancia.',
            'price' => 9.99,
            'img' => 'cannoli_siciliani.jpg',
            'visible' => true,
        ],

        // Ristorante 27
        [
            'restaurant_id' => '27',
            'name' => 'Sashimi Misto',
            'description' => 'Assortimento di pesce crudo fresco, tagliato sottile e servito con salsa di soia e wasabi.',
            'price' => 22.99,
            'img' => 'sashimi_misto.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '27',
            'name' => 'Yakitori di Pollo',
            'description' => 'Spiedini di pollo grigliati e glassati con salsa teriyaki, serviti con riso al vapore.',
            'price' => 16.99,
            'img' => 'yakitori_pollo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '27',
            'name' => 'Tempura di Gamberi',
            'description' => 'Gamberi freschi immersi in pastella leggera e fritti fino a doratura, serviti con salsa di immersione.',
            'price' => 18.99,
            'img' => 'tempura_gamberi.jpg',
            'visible' => true,
        ],

        // Ristorante 28
        [
            'restaurant_id' => '28',
            'name' => 'Ribollita Toscano',
            'description' => 'Zuppa toscana tradizionale con verdure di stagione, pane raffermo e fagioli cannellini.',
            'price' => 12.99,
            'img' => 'ribollita_toscano.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '28',
            'name' => 'Tagliata di Manzo',
            'description' => 'Trancio di manzo alla griglia servito su un letto di rucola e scaglie di Parmigiano Reggiano.',
            'price' => 26.99,
            'img' => 'tagliata_manzo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '28',
            'name' => 'Tiramisù Tradizionale',
            'description' => 'Dolce italiano composto da savoiardi inzuppati nel caffè, crema al mascarpone e cacao amaro.',
            'price' => 8.99,
            'img' => 'tiramisu_tradizionale.jpg',
            'visible' => true,
        ],

        // Ristorante 29
        [
            'restaurant_id' => '29',
            'name' => 'Pizza Margherita',
            'description' => 'Pizza classica con pomodoro, mozzarella e basilico fresco.',
            'price' => 10.99,
            'img' => 'pizza_margherita.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '29',
            'name' => 'Spaghetti Carbonara',
            'description' => 'Pasta con pancetta croccante, uova, pecorino e pepe nero.',
            'price' => 14.99,
            'img' => 'spaghetti_carbonara.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '29',
            'name' => 'Torta della Nonna',
            'description' => 'Torta rustica con crema pasticcera, pinoli e scorza di limone, coperta di zucchero a velo.',
            'price' => 7.99,
            'img' => 'torta_nonna.jpg',
            'visible' => true,
        ],

        // Ristorante 30
        [
            'restaurant_id' => '30',
            'name' => 'Sushi Sashimi Combo',
            'description' => 'Assortimento di sushi e sashimi freschi, accompagnati da riso e salsa di soia.',
            'price' => 32.99,
            'img' => 'sushi_sashimi_combo.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '30',
            'name' => 'Uramaki California Roll',
            'description' => 'Rotolo di sushi con gamberetti, avocado, cetriolo e maionese, ricoperto di sesamo.',
            'price' => 18.99,
            'img' => 'uramaki_california_roll.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '30',
            'name' => 'Miso Soup',
            'description' => 'Zuppa giapponese leggera e salata a base di brodo di miso, alghe e tofu.',
            'price' => 5.99,
            'img' => 'miso_soup.jpg',
            'visible' => true,
        ],

        // Ristorante 31
        [
            'restaurant_id' => '31',
            'name' => 'Pad Thai Gamberi',
            'description' => 'Noodle di riso saltati con gamberi freschi, uova, cipolle, germogli di soia e arachidi.',
            'price' => 16.99,
            'img' => 'pad_thai_gamberi.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '31',
            'name' => 'Gyoza di Verdure',
            'description' => 'Ravioli giapponesi fritti ripieni di verdure tritate e aromi orientali, serviti con salsa ponzu.',
            'price' => 12.99,
            'img' => 'gyoza_verdure.jpg',
            'visible' => true,
        ],
        [
            'restaurant_id' => '31',
            'name' => 'Sake Nigiri',
            'description' => 'Salmone fresco su cuscino di riso delicatamente condito, accompagnato da wasabi e zenzero.',
            'price' => 9.99,
            'img' => 'sake_nigiri.jpg',
            'visible' => true,
        ],
    ];
