<?php

return [
    [
        'user_id' => '1',
        'name' => 'Trattoria delle Eccellenze di Eugenio',
        'description' => 'Un accogliente ristorante che serve cucina italiana autentica.',
        'city' => 'Roma',
        'address' => 'Via Roma, 123',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 06 1234567',
        'website' => 'http://www.ristoranteDaEugenio.com',
        'category' => ['1']
    ],
    [
        'user_id' => '2',
        'name' => 'Marco\'s Mamma Mia Trattoria',
        'description' => 'Specialità toscane in un ambiente accogliente nel cuore di Firenze.',
        'city' => 'Firenze',
        'address' => 'Piazza del Duomo, 1',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 055 7654321',
        'website' => 'http://www.ledelizieDiMarco.it',
        'category' => ['1', '3']
    ],
    [
        'user_id' => '3',
        'name' => 'Ristorante Raoul & la Cucina del Giappone',
        'description' => 'Sushi fresco e fusion food in un ambiente moderno e chic.',
        'city' => 'Milano',
        'address' => 'Via Milano, 456',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 02 9876543',
        'website' => 'http://www.sushiRaoul.com',
        'category' => ['2', '1']
    ],
    [
        'user_id' => '4',
        'name' => 'Trattoria Francesco: Il Gusto Autentico',
        'description' => 'Piatti tradizionali della cucina emiliana preparati con amore.',
        'city' => 'Bologna',
        'address' => 'Via Bolognese, 789',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 051 2345678',
        'website' => 'http://www.NonnoFrancesco.it',
        'category' => ['4']
    ],
    [
        'user_id' => '5',
        'name' => 'Ristorante l\'ultimo arrivato da Giorgio',
        'description' => 'Autentica cucina Milanese con un\'attenzione particolare ai frutti di mare.',
        'city' => 'Milano',
        'address' => 'Via Lisbona, 101',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+351 21 8765432',
        'website' => 'http://www.GiorgioAtlantico.it',
        'category' => ['3']
    ],
    [
        'user_id' => '6',
        'name' => 'Città del Dragone',
        'description' => 'Ristorante cinese con cucina cantonese e specialità di pesce, situato a Torino.',
        'city' => 'Torino',
        'address' => 'Via Cigna, 28, 10155 Torino TO',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 011 1234567',
        'website' => 'https://www.cittadeldragone.it/',
        'category' => ['1', '6']
    ],
    [
        'user_id' => '7',
        'name' => 'Speedy Pizza',
        'description' => 'Pizzeria con consegna rapida a domicilio, offrendo una vasta gamma di pizze classiche e speciali.',
        'city' => 'Roma',
        'address' => 'Via Napoli, 15, 00100 Roma RM',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 06 1234567',
        'website' => 'https://www.speedypizzaroma.it/',
        'category' => ['1']
    ],
    [
        'user_id' => '8',
        'name' => 'Mega Grill',
        'description' => 'Ristorante specializzato in bistecche alla griglia, offrendo una vasta selezione di carni e contorni.',
        'city' => 'Milano',
        'address' => 'Via Monte Rosa, 50, 20149 Milano MI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 02 1234567',
        'website' => 'https://www.megagrillmilano.it/',
        'category' => ['7', '9', '10']
    ],
    [
        'user_id' => '9',
        'name' => 'Gusto Greco',
        'description' => 'Ristorante greco con piatti tradizionali come souvlaki, gyros e moussaka.',
        'city' => 'Firenze',
        'address' => 'Via Sant\'Egidio, 10, 50123 Firenze FI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 055 1234567',
        'website' => 'https://www.gustogrecofirenze.it/',
        'category' => ['8']
    ],
    [
        'user_id' => '10',
        'name' => 'Veloce & Saporito',
        'description' => 'Ristorante fast food con una varietà di panini, insalate, e piatti pronti da asporto o da consumare sul posto.',
        'city' => 'Napoli',
        'address' => 'Via Roma, 20, 80100 Napoli NA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 081 1234567',
        'website' => 'https://www.velocesaporito.it/',
        'category' => ['7']
    ],
    [
        'user_id' => '11',
        'name' => 'La Rustica',
        'description' => 'Pizzeria e ristorante con specialità di pizza rustica, pasta fresca e piatti tipici italiani.',
        'city' => 'Roma',
        'address' => 'Via Appia, 30, 00100 Roma RM',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 06 1234567',
        'website' => 'https://www.larusticaroma.it/',
        'category' => ['1', '10']
    ],
    [
        'user_id' => '12',
        'name' => 'Osteria del Sole',
        'description' => 'Accogliente osteria bolognese con cucina tradizionale emiliana e vasta selezione di vini locali.',
        'city' => 'Bologna',
        'address' => 'Via Mascarella, 20, 40100 Bologna BO',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 051 1234567',
        'website' => 'https://www.osteriadelsole.it/',
        'category' => ['1']
    ],
    [
        'user_id' => '13',
        'name' => 'Peking Duck',
        'description' => 'Ristorante cinese di lusso con specialità come anatra alla pechinese e piatti imperiali.',
        'city' => 'Milano',
        'address' => 'Via della Moscova, 25, 20121 Milano MI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 02 1234567',
        'website' => 'https://www.pekingduckmilano.it/',
        'category' => ['6']
    ],
    [
        'user_id' => '14',
        'name' => 'Ristorante Sakura',
        'description' => 'Ristorante giapponese con autentica cucina tradizionale, sushi fresco e piatti creativi.',
        'city' => 'Roma',
        'address' => 'Via delle Grazie, 10, 00100 Roma RM',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 06 1234567',
        'website' => 'https://www.ristorantesakura.it/',
        'category' => ['3', '6']
    ],
    [
        'user_id' => '15',
        'name' => 'Fast Pizza Express',
        'description' => 'Pizzeria con servizio di consegna rapida e pizza a taglio sempre calda e gustosa.',
        'city' => 'Napoli',
        'address' => 'Via Toledo, 50, 80100 Napoli NA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 081 1234567',
        'website' => 'https://www.fastpizzaexpress.it/',
        'category' => ['7', '10']
    ],
    [
        'user_id' => '16',
        'name' => 'Ristorante Amalfi',
        'description' => 'Cucina italiana autentica con piatti della tradizione campana, situato sulla costa di Amalfi.',
        'city' => 'Amalfi',
        'address' => 'Via Positano, 15, 84011 Amalfi SA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 089 1234567',
        'website' => 'https://www.ristoranteamalfi.it/',
        'category' => ['1', '10']
    ],
    [
        'user_id' => '17',
        'name' => 'Casa del Taco',
        'description' => 'Autentica cucina messicana con tacos, burritos, e margarita, situato nel cuore di Roma.',
        'city' => 'Roma',
        'address' => 'Via Guadalupe, 5, 00100 Roma RM',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 06 1234567',
        'website' => 'https://www.casadeltacoroma.it/',
        'category' => ['2', '7', '9']
    ],
    [
        'user_id' => '18',
        'name' => 'Sushi Master',
        'description' => 'Ristorante giapponese con sushi fresco e creativo, preparato da chef esperti, situato a Milano.',
        'city' => 'Milano',
        'address' => 'Via Nagoya, 10, 20100 Milano MI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 02 1234567',
        'website' => 'https://www.sushimastermilano.it/',
        'category' => ['3']
    ],
    [
        'user_id' => '19',
        'name' => 'Taj Mahal',
        'description' => 'Cucina indiana autentica con curry, biryani e naan, situato nel centro storico di Firenze.',
        'city' => 'Firenze',
        'address' => 'Via Jaipur, 20, 50100 Firenze FI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 055 1234567',
        'website' => 'https://www.tajmahalfirenze.it/',
        'category' => ['4']
    ],
    [
        'user_id' => '20',
        'name' => 'Green Garden',
        'description' => 'Ristorante vegetariano con menu stagionale e ingredienti freschi, situato a Bologna.',
        'city' => 'Bologna',
        'address' => 'Via delle Erbe, 5, 40100 Bologna BO',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 051 1234567',
        'website' => 'https://www.greengardenbologna.it/',
        'category' => ['5']
    ],
    [
        'user_id' => '21',
        'name' => 'Great Wall',
        'description' => 'Ristorante cinese con menu completo e varietà di piatti regionali, situato a Milano.',
        'city' => 'Milano',
        'address' => 'Via Beijing, 8, 20100 Milano MI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 02 1234567',
        'website' => 'https://www.greatwallmilano.it/',
        'category' => ['1', '6']
    ],
    [
        'user_id' => '22',
        'name' => 'Burger King',
        'description' => 'Catena internazionale di hamburger fast food, nota per i suoi burger flame-grilled.',
        'city' => 'Roma',
        'address' => 'Via Hamburg, 12, 00100 Roma RM',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 06 1234567',
        'website' => 'https://www.burgerkingroma.it/',
        'category' => ['7', '9']
    ],
    [
        'user_id' => '23',
        'name' => 'Olive Garden',
        'description' => 'Ristorante americano con cucina tex-mex e piatti barbecue, situato a Napoli.',
        'city' => 'Napoli',
        'address' => 'Via Texas, 30, 80100 Napoli NA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 081 1234567',
        'website' => 'https://www.olivegardennapoli.it/',
        'category' => ['2', '5']
    ],
    [
        'user_id' => '24',
        'name' => 'Fuego Latino',
        'description' => 'Ristorante sudamericano con specialità di carne alla griglia e cocktail esotici, situato a Firenze.',
        'city' => 'Firenze',
        'address' => 'Via Rio de Janeiro, 15, 50100 Firenze FI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 055 1234567',
        'website' => 'https://www.fuegolatinofirenze.it/',
        'category' => ['2']
    ],
    [
        'user_id' => '25',
        'name' => 'Taste of India',
        'description' => 'Ristorante indiano con cucina autentica e atmosfera accogliente, situato a Bari.',
        'city' => 'Bari',
        'address' => 'Via Mumbai, 10, 70100 Bari BA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 080 1234567',
        'website' => 'https://www.tasteofindiabari.it/',
        'category' => ['4', '5']
    ],
    [
        'user_id' => '26',
        'name' => 'Ristorante Romantico',
        'description' => 'Ambiente elegante e romantico con cucina italiana raffinata e vini pregiati, situato a Verona.',
        'city' => 'Verona',
        'address' => 'Corso Porta Nuova, 10, 37100 Verona VR',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 045 1234567',
        'website' => 'https://www.ristoranteromanticoverona.it/',
        'category' => ['1', '5']
    ],
    [
        'user_id' => '27',
        'name' => 'Sushi & Sashimi',
        'description' => 'Ristorante giapponese con sushi fresco, sashimi e altre specialità, situato a Genova.',
        'city' => 'Genova',
        'address' => 'Via Tokyo, 5, 16100 Genova GE',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 010 1234567',
        'website' => 'https://www.sushisashimigenova.it/',
        'category' => ['3', '5', '6']
    ],
    [
        'user_id' => '28',
        'name' => 'Taverna Toscana',
        'description' => 'Ristorante toscano con piatti tradizionali come ribollita, bistecca alla fiorentina e pappa al pomodoro, situato a Siena.',
        'city' => 'Siena',
        'address' => 'Piazza del Campo, 1, 53100 Siena SI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 0577 1234567',
        'website' => 'https://www.tavernatoscanasiena.it/',
        'category' => ['1', '7', '10']
    ],
    [
        'user_id' => '29',
        'name' => 'Ristorante del Mare',
        'description' => 'Cucina di mare fresca e prelibata con vista sul porto, situato a Napoli.',
        'city' => 'Napoli',
        'address' => 'Via dei Pescatori, 20, 80100 Napoli NA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 081 1234567',
        'website' => 'https://www.ristorantedelmarenapoli.it/',
        'category' => ['1']
    ],
    [
        'user_id' => '30',
        'name' => 'Il Gusto di Sicilia',
        'description' => 'Ristorante siciliano con specialità come arancini, caponata e cannoli, situato a Palermo.',
        'city' => 'Palermo',
        'address' => 'Via Sicilia, 30, 90100 Palermo PA',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 091 1234567',
        'website' => 'https://www.ilgustodisiciliapalermo.it/',
        'category' => ['1', '7', '10']
    ],
    [
        'user_id' => '31',
        'name' => 'Piazza Pizza',
        'description' => 'Pizzeria tradizionale con forno a legna e ampia selezione di pizze classiche e gourmet, situata a Firenze.',
        'city' => 'Firenze',
        'address' => 'Piazza della Signoria, 1, 50100 Firenze FI',
        'img' => 'https://via.placeholder.com/200',
        'telephone' => '+39 055 1234567',
        'website' => 'https://www.piazzapizzafirenze.it/',
        'category' => ['1', '5', '7', '10']
    ],

];
